name: build
on:
  push:
    branches:
      - "*"
      - "!master"
      - "!main"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"

      - name: Build with Maven
        run: mvn -B verify

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2

      - name: yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: yarn test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test

      - name: yarn build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
